/*
 * LED.c
 *
 * Created: 20-03-2015 15:18:13
 *  Author: s113570
 */ 

#include "LED.h"


void LED_Init(void)
{
	//Timer inits 
	
	// RED
	PORT->Group[1].PMUX[4].bit.PMUXE = 0x05;
	PORT->Group[1].PINCFG[8].bit.PMUXEN = 1;
	PM->APBCMASK.bit.TC4_=1;
	GCLK->CLKCTRL.reg = GCLK_CLKCTRL_CLKEN | GCLK_CLKCTRL_GEN_GCLK0 | GCLK_CLKCTRL_ID_TC4_TC5;
	TC4->COUNT16.CTRLC.bit.INVEN0=1;
	TC4->COUNT16.CTRLA.bit.MODE = 0x00;
	TC4->COUNT16.CTRLA.bit.PRESCALER = 0x00;
	TC4->COUNT16.CTRLA.bit.WAVEGEN = 0x02;
	TC4->COUNT16.CC[0].bit.CC = 1;
	TC4->COUNT16.CTRLA.bit.ENABLE = 1;
	
	
	// GREEN
	PORT->Group[1].PMUX[5].bit.PMUXE = 0x05;
	PORT->Group[1].PINCFG[10].bit.PMUXEN = 1;
	PM->APBCMASK.bit.TC5_=1;
	GCLK->CLKCTRL.reg = GCLK_CLKCTRL_CLKEN | GCLK_CLKCTRL_GEN_GCLK0 | GCLK_CLKCTRL_ID_TC4_TC5;
	TC5->COUNT16.CTRLC.bit.INVEN0=1;
	TC5->COUNT16.CTRLA.bit.MODE = 0x00;
	TC5->COUNT16.CTRLA.bit.PRESCALER = 0x00;
	TC5->COUNT16.CTRLA.bit.WAVEGEN = 0x02;
	TC5->COUNT16.CC[0].bit.CC = 1;
	TC5->COUNT16.CTRLA.bit.ENABLE = 1;
	
	
	//BLUE
	PORT->Group[0].PMUX[6].bit.PMUXE = 0x04;
	PORT->Group[0].PINCFG[12].bit.PMUXEN = 1;
	PM->APBCMASK.bit.TC2_ = 1;
	GCLK->CLKCTRL.reg = GCLK_CLKCTRL_CLKEN | GCLK_CLKCTRL_GEN_GCLK0 | GCLK_CLKCTRL_ID_TC2_TC3;
	TC2->COUNT16.CTRLC.bit.INVEN0=1;
	TC2->COUNT16.CTRLA.bit.MODE = 0x00;
	TC2->COUNT16.CTRLA.bit.PRESCALER = 0x00;
	TC2->COUNT16.CTRLA.bit.WAVEGEN = 0x02;
	TC2->COUNT16.CC[0].bit.CC = 1;
	TC2->COUNT16.CTRLA.bit.ENABLE = 1;
}



void LED_Set_Color(uint32_t Hex_Color_Code)
{
	//Red
	TC4->COUNT16.CC[0].bit.CC = (Hex_Color_Code>>16 & MASK_8BIT)*LED_SCALE_FACTOR;
	//Green
	TC5->COUNT16.CC[0].bit.CC = (Hex_Color_Code>>8 & MASK_8BIT)*LED_SCALE_FACTOR;
	//Blue
	TC2->COUNT16.CC[0].bit.CC = (Hex_Color_Code>>0 & MASK_8BIT)*LED_SCALE_FACTOR;
}


void LED_Set_Color_RGB(uint32_t Red, uint32_t Green, uint32_t Blue)
{
	//Red
	TC4->COUNT16.CC[0].bit.CC = Red*LED_SCALE_FACTOR;
	//Green
	TC5->COUNT16.CC[0].bit.CC = Green*LED_SCALE_FACTOR;
	//Blue
	TC2->COUNT16.CC[0].bit.CC = Blue*LED_SCALE_FACTOR;
}